export interface ExampleSentence {
  text: string;
  source: string; // e.g., "The New York Times", "The Atlantic"
  url?: string;
}

export interface WordContext {
  contextType: string; // e.g., "Legal", "Medical", "Literary"
  definition: string;
}

export interface WordData {
  id: string;
  word: string;
  definitions: WordContext[];
  examples: ExampleSentence[];
  synonyms: string[];
  etymology: string;
  aiMnemonic: string;
  userMnemonic?: string;
  aiImageUrl?: string; 
  mastered: boolean;
  isCustom?: boolean; // New flag: true if user added this word manually (even if duplicate)
  lastReview?: number;
  // SRS Fields
  leitnerBox: number; // 0 = New, 1..5 = Review Intervals
  nextReviewDate: number; // Timestamp
}

export interface ReadingArticle {
  title: string;
  summary: string;
  url: string;
  source: string;
}

export enum ViewState {
  DASHBOARD = 'DASHBOARD',
  STUDY = 'STUDY',
  READING = 'READING',
  LIBRARY = 'LIBRARY',
  ADD_WORD = 'ADD_WORD',
  SETTINGS = 'SETTINGS',
}

export interface AppState {
  words: WordData[];
  streak: number;
  lastLoginDate: string; // YYYY-MM-DD
  dailyGoal: number; // number of cards to review
  dailyProgress: number;
  darkMode: boolean;
}

// Consolidated list of High-Frequency GRE Words (Barron's 333 + Greg Mat Common Groups)
export const INITIAL_WORDS_LIST: string[] = [
  "abate", "abject", "aberrant", "abeyance", "abjure", "abnegation", "abrogate", "abscond", 
  "abstemious", "abstruse", "accede", "accretion", "acerbic", "acumen", "adamant", "admonish", 
  "adulterate", "adumbrate", "adverse", "advocate", "aesthetic", "affable", "affected", "aggrandize", 
  "alacrity", "alleviate", "amalgamate", "ambiguous", "ambivalence", "ameliorate", "amenable", 
  "amiable", "amortize", "anachronism", "analogous", "anarchy", "anathema", "ancillary", "animus", 
  "anomalous", "antagonize", "antipathy", "apathy", "apocryphal", "apogee", "appease", "apposite", 
  "apprise", "approbation", "appropriate", "arbitrary", "arcane", "archaic", "arduous", "articulate", 
  "artless", "ascetic", "asperity", "aspersion", "assiduous", "assuage", "astringent", "attenuate", 
  "audacious", "augment", "august", "auspicious", "austere", "autonomous", "avarice", "aver", "axiom", 
  "banal", "baneful", "belie", "belligerent", "beneficent", "benevolent", "benign", "berate", 
  "bereft", "bifurcate", "bilk", "blighted", "blithe", "boisterous", "bolster", "bombastic", 
  "boorish", "brook", "bucolic", "burgeon", "burnish", "buttress", "cacophony", "cajole", 
  "calamity", "calumny", "candid", "canon", "cant", "canvass", "capacious", "capital", "capitulate", 
  "capricious", "cardinal", "castigation", "catalyst", "cathartic", "caustic", "censure", "chary", 
  "chastise", "chicanery", "chimerical", "choleric", "chronological", "circuitous", "circumscribe", 
  "circumspect", "clamber", "clamor", "clandestine", "cloying", "coagulate", "coalesce", "coda", 
  "cogent", "cognizant", "commensurate", "compendium", "complaisant", "compliant", "complicity", 
  "composure", "compound", "comprehensive", "concede", "conciliatory", "concond", "condone", 
  "conducive", "conflagration", "conflate", "confound", "congenial", "connoisseur", "consecrate", 
  "consequential", "console", "conspicuous", "consternation", "consummate", "contend", "contentious", 
  "context", "contiguous", "contrite", "contumacious", "conundrum", "conventional", "converge", 
  "convoluted", "copious", "corroborate", "cosmopolitan", "countenance", "counterintuitive", 
  "counterpoint", "counterproductive", "covert", "crafty", "craven", "credibility", "credulous", 
  "crescendo", "culminate", "culpable", "cumbersome", "cupidity", "curmudgeon", "cynicism", "daunt", 
  "dearth", "debacle", "debase", "debunk", "decorum", "deem", "deface", "defamatory", "default", 
  "deference", "defiant", "deficiency", "deflect", "deft", "defunct", "defy", "degenerate", 
  "degrade", "deleterious", "delineate", "delude", "demur", "denigrate", "denounce", "deny", 
  "depict", "deplore", "deprecate", "deride", "derivative", "desiccate", "designate", "desolate", 
  "despair", "desperate", "despondent", "despot", "destitute", "desultory", "detach", "deter", 
  "deteriorate", "determinant", "detrimental", "devastate", "deviate", "devious", "devise", 
  "diatribe", "dichotomy", "dictate", "didactic", "diffident", "diffuse", "digress", "dilapidated", 
  "dilate", "dilettante", "diligent", "diminish", "diminutive", "din", "dire", "dirge", "disabuse", 
  "disaffect", "disavow", "discern", "discomfit", "disconcerting", "discordant", "discredit", 
  "discrepancy", "discrete", "discriminating", "discursive", "disdain", "disingenuous", "disinterested", 
  "disjointed", "dismantle", "dismiss", "disparage", "disparate", "dispassionate", "dispatch", 
  "dispel", "dispense", "disperse", "displace", "disposition", "disproportionate", "disregard", 
  "dissemble", "disseminate", "dissent", "dissipation", "dissolution", "dissonance", "distend", 
  "distill", "distinct", "distinguish", "distort", "distract", "diverge", "diverse", "divest", 
  "divine", "divisive", "divulge", "docile", "doctrinaire", "dogmatic", "dormant", "dour", "draconian", 
  "dramatic", "droll", "dubious", "dupe", "duplicity", "durable", "duress", "dwindle", "ebullient", 
  "eccentric", "eclectic", "eclipse", "economy", "edify", "efface", "effectual", "efficacy", "effrontery", 
  "egoism", "egregious", "elaborate", "elated", "elegy", "elicit", "elitist", "elucidate", "elusive", 
  "embellish", "eminent", "empirical", "emulate", "encompass", "encumber", "endemic", "endorse", 
  "endure", "enervate", "engender", "enhance", "enigma", "enjoin", "enormity", "entitlement", "entreat", 
  "ephemeral", "epicure", "episodic", "epistolary", "epitome", "equanimity", "equitable", "equivocate", 
  "eradicate", "erratic", "erroneous", "erudite", "eschew", "esoteric", "espouse", "estimable", 
  "estrange", "ethereal", "ethos", "eulogy", "euphemism", "euphoria", "evanescent", "evasive", 
  "evoke", "exacerbate", "exact", "exacting", "exalt", "exasperate", "excise", "exculpate", 
  "execrable", "execute", "exemplary", "exemplify", "exempt", "exhaustive", "exhilarating", 
  "exhort", "exigent", "exonerate", "exorbitant", "exotic", "expansive", "expedite", "expedient", 
  "explicit", "exploit", "exponent", "expound", "exposure", "expurgate", "exquisite", "extant", 
  "extend", "extent", "extenuate", "extol", "extraneous", "extrapolate", "extravagant", "extricate", 
  "extrinsic", "exuberant", "fabricate", "facetious", "facilitate", "fallacious", "falter", 
  "fanatical", "fanciful", "fastidious", "fathom", "fatuous", "fawning", "feasible", "fecund", 
  "feign", "felicitous", "fervent", "fervor", "fickle", "figurative", "figurehead", "finagle", 
  "finesse", "finicky", "fitful", "flag", "flagrant", "flamboyant", "flatter", "flaunt", "fledgling", 
  "fleece", "flexible", "flippant", "florid", "flout", "fluctuate", "fluent", "flummox", "foment", 
  "forage", "forbear", "forebode", "forestall", "forfeit", "forge", "forgo", "formidable", "forsake", 
  "forthright", "fortuitous", "foster", "fractious", "fragmentary", "frank", "fraudulent", 
  "frivolous", "frugal", "frustrate", "fulminate", "fund", "furious", "furtive", "futile", 
  "gainsay", "gall", "galvanize", "gambol", "garble", "garner", "garrulous", "gauche", "gaudy", 
  "generic", "genial", "genre", "germane", "gestation", "gibberish", "glacial", "glib", "glower", 
  "glutton", "goad", "gouging", "grandiloquent", "grandiose", "gratify", "gratuitous", "gregarious", 
  "grievous", "grouse", "grovel", "guile", "gullible", "hackneyed", "halcyon", "hamper", "hapless", 
  "harangue", "harbor", "hardy", "harmony", "harrowing", "haughty", "haven", "havoc", "hearken", 
  "hedonism", "hegemony", "heinous", "heretic", "hesitant", "heterogeneous", "hew", "hierarchy", 
  "hinder", "histrionic", "hoary", "homage", "homogeneous", "hoodwink", "humility", "husband", 
  "hyperbole", "hypocritical", "iconoclast", "ideology", "idiosyncrasy", "idle", "idolatry", 
  "ignominy", "illicit", "illuminate", "illusory", "illustrate", "imbibe", "imbue", "immaculate", 
  "imminent", "immutable", "impair", "impartial", "impassable", "impassive", "impeach", "impeccable", 
  "impede", "impediment", "imperative", "imperious", "imperturbable", "impervious", "impetuous", 
  "impious", "implacable", "implant", "implausible", "implement", "implicate", "implicit", "implode", 
  "implore", "importune", "impose", "imposing", "impoverished", "impracticable", "imprecation", 
  "impregnable", "impressionable", "improvident", "improvise", "impudent", "impugn", "impulsive", 
  "inadvertent", "inalienable", "inane", "inanimate", "inaugurate", "incandescent", "incantation", 
  "incarnate", "incendiary", "incense", "incentive", "incessant", "inchoate", "incidental", 
  "incipient", "incisive", "incite", "incline", "inclusive", "incoherent", "incongruous", 
  "inconsequential", "inconspicuous", "incontrovertible", "incorporate", "incorrigible", 
  "incredulous", "increment", "incumbent", "incur", "indefatigable", "indelible", "indeterminate", 
  "indifferent", "indigenous", "indigent", "indignant", "indiscriminate", "indispensable", 
  "indolent", "indomitable", "induce", "indulgent", "ineffable", "inept", "inert", "inevitable", 
  "inexorable", "inexplicable", "infallible", "infamous", "infer", "infinitesimal", "infirmity", 
  "inflammatory", "influence", "inform", "infraction", "ingenious", "ingenuous", "ingrained", 
  "ingrate", "ingratiate", "inherent", "inhibit", "inimical", "imitate", "initiate", "injurious", 
  "innate", "innocuous", "innovative", "inordinate", "inquiry", "insatiable", "inscrutable", 
  "insensible", "insidious", "insightful", "insinuate", "insipid", "insolent", "solvent", 
  "insouciant", "inspire", "instigate", "instill", "insular", "insuperable", "insure", "insurgent", 
  "insurrection", "intact", "integral", "integrate", "integrity", "intelligible", "intemperate", 
  "intensify", "inter", "interdict", "interim", "interlocutor", "intermittent", "interplay", 
  "interrogate", "intersperse", "intervene", "intimate", "intimidate", "intractable", "intransigent", 
  "intrepid", "intricate", "intrigue", "intrinsic", "introspective", "inundate", "inure", "invalid", 
  "invective", "inveigle", "invest", "invidious", "invigorate", "invincible", "inviolate", "invoke", 
  "irascible", "irate", "irony", "irrational", "irrelevant", "irresolute", "irreverent", "itinerant", 
  "jaded", "jargon", "jaundice", "jeopardy", "jettison", "jingoism", "jocular", "jubilation", 
  "judicious", "juncture", "justification", "juxtapose", "keen", "kindle", "kinetic", "knell", 
  "kudos", "labyrinth", "lachrymose", "lackluster", "laconic", "lament", "lampoon", "languid", 
  "largess", "lassitude", "latent", "laud", "lavish", "leery", "legacy", "legitimate", "lethargic", 
  "levity", "libel", "liberal", "liberate", "libertine", "license", "licentious", "limpid", "lionize", 
  "listless", "litany", "literal", "litigant", "litigation", "loathe", "lofty", "log", "loquacious", 
  "lucid", "lucrative", "ludicrous", "lugubrious", "lull", "lumber", "luminous", "lurk", "machination", 
  "magnanimous", "magnate", "magnitude", "maintain", "maladroit", "malady", "malevolent", "malign", 
  "malinger", "malleable", "mandate", "manifest", "manifold", "manipulate", "mar", "marginal", 
  "martial", "martinet", "mask", "maverick", "mawkish", "meager", "mean", "meander", "meddlesome", 
  "mediate", "mediocre", "meditate", "melancholy", "melee", "mellifluous", "memoir", "mendacious", 
  "mendicant", "mercurial", "meretricious", "merger", "merit", "metamorphosis", "metaphor", 
  "meticulous", "mettle", "microcosm", "migrant", "migrate", "milieu", "mimic", "minatory", 
  "mince", "minute", "mirth", "misanthrope", "misconstrue", "miser", "misnomer", "misogynist", 
  "mitigate", "mock", "mode", "moderate", "modest", "modicum", "mollify", "momentous", "monarchy", 
  "monastic", "monetary", "monochromatic", "monolithic", "monotony", "moral", "moratorium", 
  "morbid", "mordant", "mores", "morose", "motivate", "motley", "mundane", "munificent", "mutable", 
  "muted", "myopic", "myriad", "nadir", "naive", "narcissism", "nascent", "natter", "nebulous", 
  "necessitate", "nefarious", "negate", "negligent", "neophyte", "nepotism", "nettle", "neutral", 
  "nicety", "niche", "niggardly", "nihilism", "noisome", "nomadic", "nominal", "nonchalant", 
  "nondescript", "nonentity", "nonplus", "norm", "nostalgia", "notable", "notoriety", "novel", 
  "noxious", "nuance", "nullify", "nurture", "obdurate", "obedient", "obfuscate", "objective", 
  "obligatory", "oblique", "obliterate", "oblivious", "obnoxious", "obscure", "obsequious", 
  "observant", "obsessive", "obsolete", "obstinate", "obstreperous", "obtain", "obtrusive", 
  "obtuse", "obviate", "occlude", "occult", "odious", "officious", "offset", "olfactory", "ominous", 
  "omnipresent", "omniscient", "onerous", "onset", "onus", "opaque", "opine", "opportune", 
  "opprobrium", "optimal", "optimism", "opulent", "oration", "orator", "ordain", "order", "orient", 
  "ornate", "oscillate", "ossify", "ostensible", "ostentatious", "ostracize", "oust", "outlandish", 
  "outmoded", "outspoken", "outstrip", "overshadow", "overt", "overweening", "overwhelm", "pacify", 
  "painstaking", "palatable", "palatial", "paleontology", "palette", "palliate", "pallid", 
  "panacea", "panache", "pandemic", "panegyric", "panic", "panoply", "paradigm", "paradox", 
  "paragon", "parallel", "parameter", "paramount", "paranoia", "pariah", "parity", "parlance", 
  "parody", "parry", "parsimony", "partial", "partisan", "passive", "pastiche", "patent", 
  "pathological", "pathos", "patina", "patriarch", "patronize", "paucity", "pauper", "peccadillo", 
  "pedagogue", "pedant", "pedestrian", "peerless", "pejorative", "pellucid", "penchant", "penitent", 
  "pensive", "penury", "perceptive", "percussion", "perennial", "perfect", "perfidious", 
  "perforate", "perfunctory", "perilous", "periodic", "peripatetic", "peripheral", "perish", 
  "perjury", "permeate", "pernicious", "perpetrate", "perpetual", "perpetuate", "perplex", 
  "perquisite", "personable", "perspicacious", "persuade", "pertain", "pertinacious", "pertinent", 
  "perturb", "peruse", "pervade", "pervasive", "pessimism", "petitions", "petrified", "petulant", 
  "phenomena", "philanthropic", "philistine", "phlegmatic", "phony", "pious", "pique", "pitfall", 
  "pith", "pithy", "pitiful", "pivotal", "placate", "placebo", "placid", "plagiarism", "plaintiff", 
  "plaintive", "plastic", "platitude", "plaudit", "plausible", "plethora", "pliable", "pliant", 
  "plight", "plummet", "plunder", "pluralistic", "polarize", "polemic", "policy", "polish", 
  "politic", "populist", "pore", "porous", "portend", "portent", "portrait", "portray", "poseur", 
  "posit", "posterity", "postulate", "potable", "potent", "potentate", "potential", "pragmatic", 
  "prattle", "precarious", "precedent", "precept", "precipitate", "precipitous", "precise", 
  "preclude", "precocious", "precursor", "predator", "predecessor", "predicament", "predilection", 
  "predisposed", "preeminent", "preempt", "preen", "preface", "preference", "prejudice", 
  "preliminary", "premature", "premeditated", "premonition", "preponderance", "preposterous", 
  "prerogative", "presage", "prescient", "prescribe", "prescriptive", "presence", "preservative", 
  "prestige", "presumptuous", "pretentious", "preternatural", "pretext", "prevail", "prevalent", 
  "prevaricate", "prevent", "primacy", "primary", "prime", "primeval", "primordial", "pristine", 
  "privation", "probity", "problematic", "proclivity", "procrastinate", "prodigal", "prodigious", 
  "prodigy", "profane", "profligate", "profound", "profuse", "progenitor", "progeny", "prognosis", 
  "prohibitive", "project", "proliferate", "prolific", "prolix", "prolong", "prominent", "promote", 
  "prompt", "propagate", "propensity", "prophetic", "propinquity", "propitiate", "propitious", 
  "proponent", "proportion", "proposition", "propound", "proprietary", "propriety", "prosaic", 
  "proscribe", "proselytize", "prospective", "prosperous", "protean", "protocol", "protract", 
  "provident", "provincial", "provisional", "provocative", "provoke", "prowess", "prudence", 
  "prudent", "prudish", "prune", "pry", "pseudonym", "psyche", "publicize", "puerile", "pugnacious", 
  "pulchritude", "punctilious", "pundit", "pungent", "punitive", "purge", "purist", "purport", 
  "purported", "purposeful", "pursue", "purview", "pusillanimous", "putrefy", "quack", "quaff", 
  "quagmire", "quaint", "qualification", "qualify", "qualms", "quandary", "quarantine", "quash", 
  "quasi", "quaver", "quell", "querulous", "query", "queue", "quibble", "quiescent", "quietude", 
  "quintessential", "quixotic", "quotidian", "raconteur", "radical", "rail", "raiment", "rally", 
  "ramale", "ramification", "ramify", "rampant", "ramshackle", "rancorous", "rankle", "rant", 
  "rapacious", "rapport", "rapprochement", "rarefied", "rash", "ratify", "ratio", "rationale", 
  "rationalize", "raucous", "ravage", "rave", "ravel", "ravenous", "raze", "reactionary", "reaffirm", 
  "realism", "realm", "reaper", "rebuff", "rebuke", "rebut", "recalcitrant", "recant", "recapitulate", 
  "recast", "receptive", "recessive", "recidivism", "reciprocal", "reciprocate", "reclaim", 
  "reclusive", "recoil", "recondite", "recount", "recourse", "recrimination", "rectify", "rectitude", 
  "recuperate", "recur", "redolent", "redoubtable", "redress", "redundant", "refine", "reflect", 
  "reform", "refractory", "refrain", "refuge", "refulgent", "refute", "regale", "regime", "regress", 
  "regulate", "rehabilitate", "reimburse", "reiterate", "rejoice", "rejuvenate", "relegate", 
  "relentless", "relevant", "relinquish", "relish", "remedial", "reminisce", "remiss", "remission", 
  "remnant", "remonstrate", "remorse", "remote", "remuneration", "renascent", "rend", "render", 
  "renegade", "renege", "renounce", "renovate", "renown", "rent", "reparation", "repartee", "repeal", 
  "repel", "repent", "repertoire", "replace", "replete", "replicate", "report", "repose", 
  "reprehensible", "represent", "repress", "reprieve", "reprimand", "reprisal", "reproach", 
  "reprobate", "reproduce", "reproof", "repudiate", "repugnant", "repulse", "repute", "requite", 
  "rescind", "resent", "reserve", "reside", "residue", "resignation", "resilience", "resolute", 
  "resolution", "resolve", "resonant", "resort", "resource", "respect", "respite", "resplendent", 
  "responsive", "restitution", "restive", "restless", "restore", "restrain", "resume", "resurge", 
  "retain", "retaliate", "retard", "reticent", "retiring", "retort", "retract", "retreat", "retrench", 
  "retribution", "retrieval", "retroactive", "retrospective", "vamp", "revelry", "revere", 
  "reverence", "reverent", "reversal", "review", "revise", "revitalize", "revive", "revoke", 
  "revulsion", "rhapsodize", "rhetoric", "ribald", "riddle", "rider", "rife", "rift", "righteous", 
  "rigid", "rigor", "rile", "robust", "rococo", "rogue", "role", "roster", "rouse", "routine", 
  "rudimentary", "rue", "ruminate", "rural", "rustic", "ruthless", "sabotage", "saccharine", 
  "sacred", "sacrilegious", "sacrosanct", "sadistic", "saga", "sagacious", "sage", "salacious", 
  "salient", "salubrious", "salutary", "salvage", "sanctimonious", "sanction", "sanctuary", 
  "sanguine", "sap", "sarcasm", "sardonic", "sate", "satiate", "satire", "satirical", "saturate", 
  "saturnine", "saunter", "savant", "savor", "savory", "scale", "scanty", "scapegoat", "scathing", 
  "schematic", "scheme", "scintilla", "scintillating", "scoff", "scope", "scorn", "scourge", 
  "scrupulous", "scrutinize", "scuttle", "seclude", "sectarian", "secular", "sedate", "sedentary", 
  "sedition", "seditious", "seduce", "sedulous", "seemly", "segment", "segregate", "seismic", 
  "select", "selective", "self-effacing", "semantic", "semblance", "seminal", "sensation", 
  "sensational", "sensible", "sensitive", "sententious", "sentient", "sentiment", "sentinel", 
  "sequel", "quester", "seraphic", "serendipity", "serene", "serrated", "servile", "servitude", 
  "setback", "settle", "sever", "severe", "shabby", "sham", "shard", "shift", "shirk", "shoddy", 
  "shortcoming", "shortsighted", "shrewd", "shun", "sidestep", "signal", "signify", "simper", 
  "simple", "simulate", "sinecure", "singular", "sinister", "sinuous", "skeptic", "skiff", "skimp", 
  "skirt", "slack", "slake", "slander", "slapdash", "sleeper", "slight", "slipshod", "sloth", 
  "slough", "slovenly", "sluggish", "smelt", "smirk", "smolder", "snicker", "snivel", "sober", 
  "sobriety", "social", "sociology", "sodden", "solace", "solemn", "solicit", "solicitous", 
  "soliloquy", "solitary", "solitude", "soluble", "solvent", "somatic", "somber", "sophisticated", 
  "sophistry", "sophomoric", "soporific", "sordid", "sound", "sovereign", "spare", "sparse", 
  "spartan", "spasm", "spawn", "specialist", "specious", "spectator", "spectrum", "speculate", 
  "spendthrift", "spheroid", "splenetic", "sporadic", "sportive", "spurious", "squalid", "squander", 
  "squelch", "staccato", "stagnant", "staid", "stalemate", "stalwart", "stamina", "stance", 
  "stanch", "standard", "stark", "static", "station", "status", "staunch", "steadfast", "stealth", 
  "stem", "stereotype", "sterile", "stifle", "stigma", "stilted", "stimulant", "stimulus", "stint", 
  "stipulate", "stoic", "stolid", "stratagem", "stratify", "strenuous", "stricture", "strident", 
  "stringent", "strive", "strut", "stultify", "stupefy", "stupor", "style", "stymie", "suave", 
  "subdue", "subjective", "subjugate", "sublime", "subliminal", "submissive", "subordinate", 
  "subpoena", "subsequent", "subservient", "subside", "subsidiary", "subsidize", "substantiate", 
  "substantive", "subsume", "subterfuge", "subtle", "subvert", "succinct", "succor", "succumb", 
  "sullied", "summary", "summit", "summon", "sumptuous", "sunder", "supercilious", "superficial", 
  "superfluous", "superior", "superimpose", "supersede", "supplant", "supplement", "supplicate", 
  "supposition", "suppress", "surfeit", "surly", "surmise", "surmount", "surpass", "surreptitious", 
  "surrogate", "surveillance", "susceptible", "suspend", "sustain", "sustenance", "suture", 
  "swagger", "swamp", "sway", "sweeping", "swindler", "sybarite", "sycophant", "symbiosis", 
  "symmetry", "sympathy", "symptom", "synergistic", "synonymous", "synopsis", "synthesis", 
  "synthetic", "table", "tacit", "taciturn", "tact", "tactics", "tactile", "taint", "talisman", 
  "tangential", "tangible", "tantamount", "tardy", "tarnish", "taunt", "taut", "tautology", 
  "tawdry", "taxing", "tedious", "teeming", "temerity", "temper", "temperament", "temperate", 
  "tempestuous", "temporal", "temporize", "tenable", "tenacious", "tendentious", "tender", "tenet", 
  "tensile", "tentative", "tenuous", "tenure", "tepid", "terminal", "terminate", "terrestrial", 
  "terse", "testify", "testimonial", "theoretical", "therapeutic", "thespian", "thwart", "timid", 
  "timorous", "tirade", "titular", "toady", "tome", "tonic", "topography", "torpid", "torpor", 
  "torque", "torrent", "torrid", "tortuous", "totter", "touchstone", "tout", "toxic", "tract", 
  "tractable", "trade", "traduce", "trajectory", "tranquil", "transcend", "transcendent", 
  "transcribe", "transgress", "transient", "transition", "transitory", "translucent", "transmute", 
  "transparent", "transport", "transpose", "trappings", "traumatic", "travail", "travesty", 
  "treacherous", "treatise", "tremulous", "trepidation", "trespass", "tribute", "trickle", 
  "trifle", "trite", "trivial", "trounce", "truce", "truculent", "truncated", "trust", "tumult", 
  "turbid", "turbulence", "turgid", "turmoil", "turncoat", "turpitude", "tycoon", "tyro", 
  "ubiquitous", "ulterior", "ultimate", "umbrage", "unaccountable", "unaffected", "unanimity", 
  "unassailable", "unassuming", "uncanny", "uncertainty", "uncharted", "unconscionable", "uncouth", 
  "unctuous", "underlying", "undermine", "underscored", "understate", "undertake", "undulate", 
  "unearth", "unequivocal", "unexceptionable", "unfeigned", "unfetter", "unflappable", "unfounded", 
  "ungainly", "uniformity", "unimpeachable", "unique", "universal", "unkempt", "unmitigated", 
  "unobtrusive", "unprecedented", "unpretentious", "unravel", "unregenerate", "unrest", "unruly", 
  "unsavory", "unscathed", "unseemly", "unsightly", "unstinting", "untenable", "unwarranted", 
  "unwieldy", "unwitting", "upbraid", "uphold", "uproarious", "upshot", "urbane", "usurp", 
  "usury", "utilitarian", "utopia", "vacillate", "vacuous", "vagary", "vagrant", "vague", "vain", 
  "valid", "validate", "valor", "vanguard", "vanity", "variegated", "varnish", "vary", "veer", 
  "vehement", "venal", "vendetta", "venerate", "venial", "venture", "veracious", "veracity", 
  "verbalize", "verbatim", "verbose", "verdant", "verge", "verisimilitude", "verity", "vernacular", 
  "versatile", "vertex", "vertical", "vertigo", "verve", "vestige", "vex", "viable", "vicarious", 
  "vice", "vicissitude", "victimize", "vie", "vigilant", "vignette", "vigor", "vilify", "vindicate", 
  "vindictive", "virtual", "virtuoso", "virulent", "visceral", "viscous", "visionary", "vital", 
  "vitiate", "vitriolic", "vituperative", "vivacious", "vivid", "vociferous", "volatile", "volition", 
  "voluble", "voluminous", "voluntary", "vortex", "vulnerable", "waffle", "waft", "wage", "waive", 
  "wake", "wane", "wanton", "warrant", "wary", "waste", "waver", "wax", "waylay", "wean", "weather", 
  "weighty", "welter", "wheedle", "whet", "whimsical", "widespread", "willful", "wily", "wince", 
  "windfall", "winnow", "winsome", "wistful", "withdraw", "wither", "withhold", "withstand", 
  "witless", "witticism", "wizardry", "woe", "worldly", "wrath", "wren", "wretch", "writ", "writhe", 
  "wrongheaded", "wry", "xenophobia", "yoke", "zany", "zeal", "zealot", "zenith", "zephyr"
];